backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"
i18n:
  structure: multiple_files
  locales: [en, zh-tw]
  default_locale: en
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    i18n: true
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", i18n: "true" }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: "duplicate" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown", i18n: "true" }
      - { label: "Tags", name: "tags", widget: "list", i18n: "true" }
      - { label: "Categories", name: "categories", widget: "list", i18n: "true" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/page/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }